name: ci_pull_request
on: pull_request
jobs:
  lint-unit-tests:
    name: Lint + Unit Tests + Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Install packages
        run: |
          flutter pub get
          cd example
          flutter pub get
      - name: Lint
        run: flutter analyze
      - name: Formatting
        run: dart format . -l 120 --set-exit-if-changed
      - name: Unit tests
        run: flutter test
